image:
  repository: dinesh150/ipl-voter
  tag: "4973f95b3a3ca37f1f22bf2abecf2ad6ea770b3a"

replicaCount: 1

service:
  type: NodePort
  port: 80
  targetPort: 5000     
  nodePort: 30007      

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

persistence:
  enabled: true
  size: 100Mi