apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ipl-voter-rules
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: ipl.voter.rules
      rules:
        - alert: HighCPUUsage
          expr: rate(process_cpu_seconds_total[5m]) > 0.8
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: High CPU Usage
            description: CPU usage has been above 80% for 2 minutes.

        - alert: HighMemoryUsage
          expr: process_resident_memory_bytes > 500000000
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: High Memory Usage
            description: Memory usage has exceeded 500 MB.

        - alert: PodNotReady
          expr: kube_pod_status_ready{condition="false"} == 1
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: Pod Not Ready
            description: One or more pods are not ready.