apiVersion: v1
kind: Service
metadata:
  name: ipl-voter
  namespace: default
  labels:
    app: ipl-voter
spec:
  selector:
    app: ipl-voter
  ports:
    - name: http
      port: 5000
      targetPort: 5000